### ISSUE TITLE
wiimote pairs but doesn't connect 

### ISSUE THREAD

**Issue by LumpyDiarrhea** [dolphin-emu/WiimotePair#3]
maybe i am doing something wrong but i can pair my wiimote and it will pair in settings but whenever i try to turn it on it just flashes i am on a macbook pro 2016 maybe i am doing something wrong idk

**Comment by Vincenzo160** [comment]
I am having the same problem, it shows up in the devices list but dolphin won't detect it.
I am on MacOS 15.1 and dolphin 2409 with continuous scanning enabled.
